package com.webblock.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.webblock.model.Product;
import com.webblock.model.SiteSetting;
import com.webblock.model.Website;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileInputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;

@Service
@Slf4j
public class GitHubRepoService {

    @Value("${github.token:}")
    private String configuredToken;

    @Value("${github.org:WebBlock-Organization}")
    private String configuredOrg;

    @Value("${ai.service.url:http://localhost:8000}")
    private String aiServiceUrl;

    private final ObjectMapper objectMapper = new ObjectMapper();
    private final HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build();

    private String getEffectiveToken() {
        if (configuredToken != null && !configuredToken.isBlank()) {
            return configuredToken.trim();
        }
        String envToken = System.getenv("GITHUB_TOKEN");
        if (envToken != null && !envToken.isBlank()) {
            return envToken.trim();
        }
        // Check Backend/.env file
        try {
            File envFile = new File("../.env");
            if (!envFile.exists()) {
                envFile = new File("/Users/sovannarith/Desktop/WebBlock/Backend/.env");
            }
            if (envFile.exists()) {
                Properties props = new Properties();
                try (FileInputStream fis = new FileInputStream(envFile)) {
                    props.load(fis);
                    String token = props.getProperty("GITHUB_TOKEN");
                    if (token != null && !token.isBlank()) return token.trim();
                }
            }
        } catch (Exception e) {
            log.warn("Could not read Backend/.env: {}", e.getMessage());
        }
        return null;
    }

    private String getEffectiveOrg() {
        if (configuredOrg != null && !configuredOrg.isBlank()) {
            return configuredOrg.trim();
        }
        String envOrg = System.getenv("GITHUB_ORG");
        if (envOrg != null && !envOrg.isBlank()) {
            return envOrg.trim();
        }
        try {
            File envFile = new File("../.env");
            if (!envFile.exists()) {
                envFile = new File("/Users/sovannarith/Desktop/WebBlock/Backend/.env");
            }
            if (envFile.exists()) {
                Properties props = new Properties();
                try (FileInputStream fis = new FileInputStream(envFile)) {
                    props.load(fis);
                    String org = props.getProperty("GITHUB_ORG");
                    if (org != null && !org.isBlank()) return org.trim();
                }
            }
        } catch (Exception e) {
            log.warn("Could not read Backend/.env: {}", e.getMessage());
        }
        return "WebBlock-Organization";
    }

    public String createAndPushTenantRepo(Website website, SiteSetting siteSetting, List<Product> products) {
        String token = getEffectiveToken();
        String org = getEffectiveOrg();
        String repoName = sanitizeRepoName(website.getSubdomain() + "-store");

        log.info("Creating and pushing GitHub repository for tenant: {} in organization: {}", repoName, org);

        String targetOwner = org;
        String repoUrl = "https://github.com/" + org + "/" + repoName;

        if (token == null || token.isBlank()) {
            log.error("GitHub token is not configured. Please set GITHUB_TOKEN in your environment or in Backend/.env");
            return repoUrl;
        }

        try {
            // 1. Create Repository via GitHub API
            Map<String, Object> createPayload = new HashMap<>();
            createPayload.put("name", repoName);
            createPayload.put("description", (website.getSubdomain() != null ? website.getSubdomain() : "WebBlock") + " Storefront (Next.js + Prisma) generated by WebBlock");
            createPayload.put("private", false);
            createPayload.put("auto_init", true);

            String createJson = objectMapper.writeValueAsString(createPayload);

            HttpRequest createReq = HttpRequest.newBuilder()
                    .uri(URI.create("https://api.github.com/orgs/" + org + "/repos"))
                    .header("Authorization", "Bearer " + token)
                    .header("Accept", "application/vnd.github+json")
                    .header("X-GitHub-Api-Version", "2022-11-28")
                    .header("User-Agent", "WebBlock-Engine")
                    .POST(HttpRequest.BodyPublishers.ofString(createJson))
                    .build();

            HttpResponse<String> createRes = httpClient.send(createReq, HttpResponse.BodyHandlers.ofString());

            if (createRes.statusCode() == 201) {
                JsonNode resJson = objectMapper.readTree(createRes.body());
                repoUrl = resJson.path("html_url").asText(repoUrl);
                targetOwner = resJson.path("owner").path("login").asText(org);
                log.info("Successfully created repo in organization: {}", repoUrl);
            } else if (createRes.statusCode() == 422) {
                // Already exists
                log.info("Repository {} already exists, proceeding to sync files.", repoName);
            } else {
                log.warn("Org creation status: {} {}. Attempting fallback to user repo creation...", createRes.statusCode(), createRes.body());
                HttpRequest userReq = HttpRequest.newBuilder()
                        .uri(URI.create("https://api.github.com/user/repos"))
                        .header("Authorization", "Bearer " + token)
                        .header("Accept", "application/vnd.github+json")
                        .header("X-GitHub-Api-Version", "2022-11-28")
                        .header("User-Agent", "WebBlock-Engine")
                        .POST(HttpRequest.BodyPublishers.ofString(createJson))
                        .build();
                HttpResponse<String> userRes = httpClient.send(userReq, HttpResponse.BodyHandlers.ofString());
                if (userRes.statusCode() == 201 || userRes.statusCode() == 422) {
                    JsonNode userJson = objectMapper.readTree(userRes.body());
                    repoUrl = userJson.path("html_url").asText("https://github.com/user/" + repoName);
                    targetOwner = userJson.path("owner").path("login").asText(targetOwner);
                }
            }

            // 2. Prepare Files for the Single-File Next.js + Prisma Storefront
            Map<String, String> filesToPush = generateStorefrontFiles(website, siteSetting, products);

            // 3. Push each file via GitHub Contents API
            for (Map.Entry<String, String> entry : filesToPush.entrySet()) {
                String path = entry.getKey();
                String content = entry.getValue();
                pushFileToRepo(token, targetOwner, repoName, path, content);
            }

            log.info("Successfully pushed all frontend & backend files to GitHub repository: {}", repoUrl);
            return repoUrl;

        } catch (Exception e) {
            log.error("Error creating/pushing GitHub repo for tenant {}: {}", website.getTenantId(), e.getMessage());
            return "https://github.com/" + org + "/" + repoName;
        }
    }

    private void pushFileToRepo(String token, String owner, String repo, String path, String content) {
        try {
            String encodedContent = Base64.getEncoder().encodeToString(content.getBytes(StandardCharsets.UTF_8));
            String existingSha = getFileSha(token, owner, repo, path);

            Map<String, Object> body = new HashMap<>();
            body.put("message", "Add / Update " + path + " via WebBlock Engine");
            body.put("content", encodedContent);
            body.put("branch", "main");
            if (existingSha != null) {
                body.put("sha", existingSha);
            }

            String jsonBody = objectMapper.writeValueAsString(body);

            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create("https://api.github.com/repos/" + owner + "/" + repo + "/contents/" + path))
                    .header("Authorization", "Bearer " + token)
                    .header("Accept", "application/vnd.github+json")
                    .header("X-GitHub-Api-Version", "2022-11-28")
                    .header("User-Agent", "WebBlock-Engine")
                    .PUT(HttpRequest.BodyPublishers.ofString(jsonBody))
                    .build();

            HttpResponse<String> res = httpClient.send(req, HttpResponse.BodyHandlers.ofString());
            if (res.statusCode() >= 200 && res.statusCode() < 300) {
                log.info("Committed file: {} to repo: {}/{}", path, owner, repo);
            } else {
                log.warn("Failed to commit file {}: status {} - {}", path, res.statusCode(), res.body());
            }
        } catch (Exception e) {
            log.error("Exception committing file {}: {}", path, e.getMessage());
        }
    }

    private String getFileSha(String token, String owner, String repo, String path) {
        try {
            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create("https://api.github.com/repos/" + owner + "/" + repo + "/contents/" + path + "?ref=main"))
                    .header("Authorization", "Bearer " + token)
                    .header("Accept", "application/vnd.github+json")
                    .header("X-GitHub-Api-Version", "2022-11-28")
                    .header("User-Agent", "WebBlock-Engine")
                    .GET()
                    .build();

            HttpResponse<String> res = httpClient.send(req, HttpResponse.BodyHandlers.ofString());
            if (res.statusCode() == 200) {
                JsonNode json = objectMapper.readTree(res.body());
                return json.path("sha").asText(null);
            }
        } catch (Exception e) {
            // File does not exist yet
        }
        return null;
    }

    private Map<String, String> generateStorefrontFiles(Website website, SiteSetting siteSetting, List<Product> products) {
        Map<String, String> files = new LinkedHashMap<>();

        String businessName = "Store";
        String contactEmail = "support@webblock.io";
        String contactPhone = "+1 (800) 555-0199";
        String heroTitle = "The Future of Tech Gear";
        String heroSubtitle = "Experience boundary-pushing audio precision, smart ergonomics, and aerospace-grade accessories designed for performance.";

        if (siteSetting != null && siteSetting.getThemeConfig() != null) {
            Map<String, Object> tc = siteSetting.getThemeConfig();
            if (tc.containsKey("businessName") && tc.get("businessName") != null && !String.valueOf(tc.get("businessName")).isBlank()) {
                businessName = String.valueOf(tc.get("businessName"));
            } else if (website.getSubdomain() != null) {
                businessName = website.getSubdomain().replace("-", " ").toUpperCase();
            }
            if (tc.containsKey("contactEmail") && tc.get("contactEmail") != null) {
                contactEmail = String.valueOf(tc.get("contactEmail"));
            }
            if (tc.containsKey("contactPhone") && tc.get("contactPhone") != null) {
                contactPhone = String.valueOf(tc.get("contactPhone"));
            }
            if (tc.containsKey("tagline") && tc.get("tagline") != null) {
                heroSubtitle = String.valueOf(tc.get("tagline"));
            }
        } else if (website.getSubdomain() != null) {
            businessName = website.getSubdomain().replace("-", " ").toUpperCase();
        }

        String initialLetter = businessName.isBlank() ? "S" : String.valueOf(businessName.trim().charAt(0)).toUpperCase();

        // 1. package.json
        files.put("package.json", """
{
  "name": "__SUBDOMAIN__-store",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "postinstall": "prisma generate"
  },
  "dependencies": {
    "@prisma/client": "^5.21.1",
    "clsx": "^2.1.1",
    "lucide-react": "^0.453.0",
    "next": "14.2.15",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tailwind-merge": "^2.5.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.47",
    "prisma": "^5.21.1",
    "tailwindcss": "^3.4.14",
    "typescript": "^5"
  }
}
""".replace("__SUBDOMAIN__", website.getSubdomain() != null ? website.getSubdomain() : "store"));

        // 2. tsconfig.json
        files.put("tsconfig.json", """
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
""");

        // 3. tailwind.config.js
        files.put("tailwind.config.js", """
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
""");

        // 4. postcss.config.js
        files.put("postcss.config.js", """
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
""");

        // 5. prisma/schema.prisma (PostgreSQL RLS Boundary)
        files.put("prisma/schema.prisma", """
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Product {
  id           String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tenantId     String   @map("tenant_id") @db.Uuid
  title        String   @db.VarChar(255)
  price        Decimal  @default(0.00) @db.Decimal(12, 2)
  status       String?  @default("ACTIVE") @db.VarChar(50)
  customFields Json?    @default("{}") @map("custom_fields")
  createdAt    DateTime @default(now()) @map("created_at") @db.Timestamptz

  @@map("products")
}

model SiteSetting {
  id                  String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tenantId            String   @unique @map("tenant_id") @db.Uuid
  themeConfig         Json?    @default("{}") @map("theme_config")
  allowedCustomFields Json?    @default("[]") @map("allowed_custom_fields")
  updatedAt           DateTime @default(now()) @updatedAt @map("updated_at") @db.Timestamptz

  @@map("site_settings")
}
""");

        // 6. .env.example
        files.put(".env.example", """
DATABASE_URL="postgresql://postgres:password@localhost:5432/webblock_db"
NEXT_PUBLIC_TENANT_ID="__TENANT_ID__"
""".replace("__TENANT_ID__", String.valueOf(website.getTenantId())));

        // 7. src/app/layout.tsx
        files.put("src/app/layout.tsx", """
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "__BUSINESS_NAME__ — Official Store",
  description: "Crafted with WebBlock Platform (Next.js + Prisma).",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="bg-[#090d16] text-slate-100 antialiased min-h-screen">
        {children}
      </body>
    </html>
  );
}
""".replace("__BUSINESS_NAME__", businessName));

        // 8. src/lib/prisma.ts (Singleton Prisma Client)
        files.put("src/lib/prisma.ts", """
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ||
  new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
""");

        // 9. src/app/api/products/route.ts (Next.js App Router API for Database Products)
        files.put("src/app/api/products/route.ts", """
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET() {
  try {
    const tenantId = process.env.NEXT_PUBLIC_TENANT_ID;
    if (!tenantId) {
      return NextResponse.json({ error: "NEXT_PUBLIC_TENANT_ID is not set in .env" }, { status: 400 });
    }

    const products = await prisma.product.findMany({
      where: {
        tenantId: tenantId,
        status: "ACTIVE",
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    return NextResponse.json(products);
  } catch (error: any) {
    console.error("Prisma error querying products:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
""");

        // 10. src/app/api/settings/route.ts (Next.js App Router API for Site Settings)
        files.put("src/app/api/settings/route.ts", """
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET() {
  try {
    const tenantId = process.env.NEXT_PUBLIC_TENANT_ID;
    if (!tenantId) {
      return NextResponse.json({ error: "NEXT_PUBLIC_TENANT_ID is not set in .env" }, { status: 400 });
    }

    const setting = await prisma.siteSetting.findUnique({
      where: {
        tenantId: tenantId,
      },
    });

    return NextResponse.json(setting || {});
  } catch (error: any) {
    console.error("Prisma error querying site settings:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
""");

        // 11. src/app/globals.css
        files.put("src/app/globals.css", """
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #090d16;
  --foreground: #f8fafc;
}

body {
  background-color: var(--background);
  color: var(--foreground);
}

.glass-card {
  background: rgba(30, 41, 59, 0.6);
  backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.08);
}
""");

        // 12. src/app/page.tsx (100% Dynamic Groq AI-Generated Tenant Storefront)
        String aiCode = fetchAiGeneratedStorefrontCode(website, businessName, heroTitle, heroSubtitle, contactEmail, contactPhone, products);
        if (aiCode != null && !aiCode.isBlank()) {
            log.info("🔥 [AI Code Generation] Successfully pushing 100% live Groq AI-generated page.tsx ({} chars) for subdomain: {}", aiCode.length(), website.getSubdomain());
            files.put("src/app/page.tsx", aiCode);
        } else {
            throw new IllegalStateException("AI Code Generation failed: Unable to generate storefront code via Groq AI model. No fallback used.");
        }

        // 13. README.md
        files.put("README.md", """
# __BUSINESS_NAME__ — Storefront

This is a standalone, production-ready e-commerce store generated automatically by the **WebBlock** platform.

## 🚀 Tech Stack
- **Frontend & Backend**: Next.js 14 App Router + Prisma ORM (Standalone Full-Stack Architecture)
- **Styling**: Tailwind CSS & Lucide Icons
- **Database**: PostgreSQL with Multi-Tenant Row-Level Security (RLS)

## 📦 Getting Started
1. Clone the repository:
   ```bash
   git clone https://github.com/__ORG__/__SUBDOMAIN__-store.git
   cd __SUBDOMAIN__-store
   ```
2. Install dependencies:
   ```bash
   npm install
   ```
3. Set up environment variables:
   ```bash
   cp .env.example .env
   ```
   Ensure your `.env` has:
   ```env
   DATABASE_URL="postgresql://postgres:password@localhost:5432/webblock_db"
   NEXT_PUBLIC_TENANT_ID="__TENANT_ID__"
   ```
4. Generate Prisma Client (runs automatically on install):
   ```bash
   npx prisma generate
   ```
5. Run locally:
   ```bash
   npm run dev
   ```
"""
                .replace("__BUSINESS_NAME__", businessName)
                .replace("__ORG__", getEffectiveOrg())
                .replace("__SUBDOMAIN__", website.getSubdomain() != null ? website.getSubdomain() : "store")
                .replace("__TENANT_ID__", String.valueOf(website.getTenantId())));

        return files;
    }

    private String sanitizeRepoName(String input) {
        if (input == null || input.isBlank()) return "store-" + UUID.randomUUID().toString().substring(0, 6);
        String clean = input.toLowerCase().replaceAll("[^a-z0-9-]", "-").replaceAll("-+", "-");
        if (clean.startsWith("-")) clean = clean.substring(1);
        if (clean.endsWith("-")) clean = clean.substring(0, clean.length() - 1);
        return clean.isBlank() ? "store-" + UUID.randomUUID().toString().substring(0, 6) : clean;
    }

    private String fetchAiGeneratedStorefrontCode(Website website, String businessName, String heroTitle, String heroSubtitle, String contactEmail, String contactPhone, List<Product> products) {
        try {
            Map<String, Object> payload = new HashMap<>();
            payload.put("subdomain", website.getSubdomain() != null ? website.getSubdomain() : "store");
            payload.put("business_name", businessName);
            payload.put("hero_title", heroTitle);
            payload.put("hero_subtitle", heroSubtitle);
            payload.put("contact_email", contactEmail);
            payload.put("contact_phone", contactPhone);
            payload.put("products", products != null ? products : Collections.emptyList());

            String jsonPayload = objectMapper.writeValueAsString(payload);

            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create(aiServiceUrl + "/api/ai/generate-storefront-code"))
                    .header("Content-Type", "application/json")
                    .timeout(Duration.ofSeconds(20))
                    .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                    .build();

            HttpResponse<String> res = httpClient.send(req, HttpResponse.BodyHandlers.ofString());
            if (res.statusCode() == 200) {
                JsonNode json = objectMapper.readTree(res.body());
                String code = json.path("page_tsx").asText(null);
                if (code != null && !code.isBlank()) {
                    log.info("Successfully received dynamic AI-generated storefront code for subdomain: {}", website.getSubdomain());
                    return code;
                }
            } else {
                log.error("AI code generator endpoint returned status {}. Cannot generate storefront code.", res.statusCode());
            }
        } catch (Exception e) {
            log.error("Could not fetch code from AI microservice: {}", e.getMessage());
        }
        return null;
    }
}
